version : "3"
services:
  db:
    container_name: python-flask-restapi-db
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
        MYSQL_DATABASE: python-flask-restapi
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user1
        MYSQL_PASSWORD: password